export const GARAGE_ACTION_TYPES = {
  SET_CARS: 'garage/SET_CARS',
  ADD_CAR: 'garage/ADD_CAR',
  UPDATE_CAR: 'garage/UPDATE_CAR',
  DELETE_CAR: 'garage/DELETE_CAR',
  SET_CURRENT_PAGE: 'garage/SET_CURRENT_PAGE',
  SET_SELECTED_CAR: 'garage/SET_SELECTED_CAR',
  SET_EDITING_CAR: 'garage/SET_EDITING_CAR',
  SET_CREATING: 'garage/SET_CREATING',
  SET_TOTAL_CARS: 'garage/SET_TOTAL_CARS',
  GENERATE_CARS: 'garage/GENERATE_CARS'
} as const;